"""Embed a GIF as an LVGL v9 raw image descriptor.

The generated source follows TuyaOpen's LVGL GIF example. The GIF decoder
reads dimensions and timing from the byte stream, so descriptor width and
height remain zero.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def render(data: bytes, symbol: str, source_name: str) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    body = "\n".join(rows)
    return f"""/*
 * Generated by tools/gif_to_lvgl_c.py from {source_name}.
 * Do not hand-edit; regenerate from media/standby.gif.
 */

#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {symbol}_map[] = {{
{body}
}};

const lv_image_dsc_t {symbol} = {{
    .header.w = 0,
    .header.h = 0,
    .header.cf = LV_COLOR_FORMAT_RAW,
    .data = {symbol}_map,
    .data_size = sizeof({symbol}_map),
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--symbol", required=True)
    args = parser.parse_args()

    data = args.input.read_bytes()
    if not data.startswith((b"GIF87a", b"GIF89a")):
        raise SystemExit(f"{args.input} is not a GIF")
    args.output.write_text(
        render(data, args.symbol, args.input.name),
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
